name: gha-result
on:
  workflow_dispatch:
  push:
    branches:
    - branch-1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: ''
    - name: Set up cache
      uses: actions/cache@v3.3.1
      with:
        path: "${{ github.workspace }}/.m2"
        key: "${{ runner.os }}-path"
    - run: mvn -q install -Dgpg.skip
    - run: mvn -q clean compile test
    - run: bash <(curl -s https://codecov.io/bash)
      if: "${{ success() }}"
    - uses: distributhor/workflow-webhook@v3.0.2
      env:
        webhook_url: "${{ secrets.WEBHOOK_URL }}"
        webhook_secret: "${{ secrets.WEBHOOK_SECRET }}"
#     # This item has no matching transformer
#     - email: false
    strategy:
      matrix:
        jdk:
        - oraclejdk11
        - oraclejdk-ea
        - openjdk11
        - openjdk-ea
#       # 'allow_failures' transformations are currently unsupported.
